language: php

php:
  - '7.2'

install:
  - composer install

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)